# Generated by Django 4.2.3 on 2023-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=30)),
                ('device_name', models.CharField(max_length=30)),
                ('issue_date', models.CharField(max_length=30)),
                ('return_date', models.CharField(max_length=30)),
            ],
        ),
    ]
